In [124]:
# Count values, lift, and MDS
import pandas as pd
def mentions(words,text):
  for word in words:
    if word not in text:
        return False
  return True
  
def allmentions(words,texts):
  mentionedcount = 0
  comentions=[]
  for text in texts:
    comention=mentions(words,text)
    if(comention):
      mentionedcount+=1
      comentions.append(True)
    else:
      comentions.append(False)
  return(mentionedcount,comentions)

def lift(countx,county,countxy,N):
  return(countxy/N)/((countx/N)*(county/N))
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize
import string

def TokenizeProcess(df,column):
    word_lemmatizer = WordNetLemmatizer()

    df_tk = pd.DataFrame(columns=[column])#columns=['ptitle', 'pscore', 'pid', 'pbody', 'pcreated', 'comment', 'cauthor', 'ccreated'])

    for comment in df.values.tolist():
        # Tokenize
        tokens = word_tokenize(str(comment))

        # Strip punctuation
        punctuation_list = str.maketrans('', '', string.punctuation)
        tokens_strp = [w.translate(punctuation_list) for w in tokens]

        # Remove other non-alphabetic tokens
        words = [word for word in tokens_strp if word.isalpha()]

        # Stop words
        stop_words = set(stopwords.words('english'))
        words = [w for w in words if not w in stop_words]

        # Lemmatize
        # Note: We might need to do this for the brands we want to detect as well
        words_lm = [word_lemmatizer.lemmatize(w) for w in words]
        df_tk = df_tk.append({column:words} ,ignore_index=True) 
    return df_tk

def GetTopN(df, words, n, word_type,columnnos,tokenize=False):
  if(tokenize==True):
    words = TokenizeProcess(df,df.columns[columnnos])
  words_count = dict.fromkeys(words, 0)  
  
  for row in df.values.tolist():
    comment = []
    for col in columnnos:
        comment.extend(row[col])
    for word in words_count:
      if word in comment:
        words_count[word] += 1
  
  words_df = pd.DataFrame.from_dict(words_count, orient='index')
  print('\nTop {} {} are:'.format(n, word_type))
  top_n_words = words_df.sort_values(by=[0], ascending=False).head(n)
  print(top_n_words)
  return top_n_words.index.tolist()



    
# def find_replace(data,column,replacements,tokenize=False):
#     new_data=[]
#     if(tokenize==True):
#         for text in data[column]:
#             text=text[1:len(text)-1].replace("'","").split(", ")
            
#     new_text=[]
#     for text in new_data:
#         for token_index in range(0,len(text)):
#             token=text[token_index]
#             if(token.lower() in replacements.keys()):
#                 text[token_index] = replacements[token.lower()]
                
#         new_text.append(text)
#     return(new_text)
    
# import nltk
# import pandas as pd
# df_tk_pre=pd.read_csv("./data/pre_soccer_tokenized.csv")
# df_tk_post=pd.read_csv("./data/post_soccer_tokenized.csv")
# replacements=pd.read_csv("./data/teams.csv")

from datetime import datetime
#pre_df = pd.read_csv('./data/pre_soccer_replaced.csv')
#post_df = pd.read_csv('./data/post_soccer_replaced.csv')

import pickle
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
df_tk_pre = pickle.load( open( "./data/pre_df_tk.p", "rb" ) )

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1076)>
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1076)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1076)>

In [104]:
df_tk_pre['ptitle'] = [text.lower() for text in df_tk_pre['ptitle']]

In [105]:
df_tk_pre['involved_teams'] = [x.split(" vs ") for x in df_tk_pre['involved_teams']]

In [ ]:
df_tk_pre[df_tk_pre['ptitle'].str.contains("real madrid")&df_tk_pre['ptitle'].str.contains("liverpool")]

In [123]:
df_tk_pre[df_tk_pre['ptitle'].str.contains("real madrid")&df_tk_pre['ptitle'].str.contains("liverpool")]

,ptitle,pscore,pid,pbody,pcreated,comment,cauthor,ccreated,pcreated_date,ccreated_date,involved_teams
11727,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,[penis],CrypticalEntity,1.527348e+09,2018-05-26 11:12:04,2018-05-26 11:14:25,[None]
11728,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[local, kebab, shop, offering, free, shawarma,...",jdotdigital,1.527362e+09,2018-05-26 11:12:04,2018-05-26 15:07:11,[None]
11729,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[like, announce, random, guy, go, auc, america...",NaN,1.527359e+09,2018-05-26 11:12:04,2018-05-26 14:16:30,[None]
11730,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[RealMadridly, wish, ox, healthy, one]",cjsssi,1.527348e+09,2018-05-26 11:12:04,2018-05-26 11:17:40,[None]
11731,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[liverpoLyon, player, make, mistake, http]",manthanpa1997,1.527351e+09,2018-05-26 11:12:04,2018-05-26 12:07:45,[None]
...,...,...,...,...,...,...,...,...,...,...,...
12927,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[fair, enough, although, point, ultras, ultra,...",JuanitoGomez,1.527373e+09,2018-05-26 11:12:04,2018-05-26 18:10:57,[None]
12928,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[picture, revisionism, http, qtbn]",JuanitoGomez,1.527373e+09,2018-05-26 11:12:04,2018-05-26 18:13:04,[None]
12929,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[idk, expected, able, read, bad]",letsgetcool,1.527365e+09,2018-05-26 11:12:04,2018-05-26 16:07:04,[None]
12930,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[every, spanish, club, big, one, also, dislike...",harea123,1.527372e+09,2018-05-26 11:12:04,2018-05-26 18:01:47,[None]
12931,pre match thread: real madrid vs. liverpool [c...,1326.0,8m8hyh,----------------------------------\n\n[](#icon...,1.527348e+09,"[enemy, enemy, friend, p]",JuanitoGomez,1.527372e+09,2018-05-26 11:12:04,2018-05-26 18:03:09,[None]

In [106]:
keywords = pd.read_csv('./data/teams.csv')
teams = list(map(str.lower, list(set(keywords.iloc[:, 0]))))
attributes = ['good','bad']

top10_team_names = GetTopN(df_tk_pre, teams, 30, 'brands',[5,len(df_tk_pre.columns)-1],tokenize=False)
top5_team_names = GetTopN(df_tk_pre, teams, 5, 'brands',[5,len(df_tk_pre.columns)-1],tokenize=False)
top5_attributes = GetTopN(df_tk_pre, attributes, 5, 'attributes',[5])
top10_attributes = GetTopN(df_tk_pre, attributes, 10, 'attributes',[5])

Top 30 brands are:
                  0
bayern          523
psg             379
ajax            368
chelsea         240
barcelona       234
arsenal         202
lyon            199
tottenham       125
inter           107
dortmund         82
leipzig          81
sevilla          74
milan            56
porto            46
shakhtar         26
benfica           5
roma              3
salzburg          2
napoli            0
manunited         0
villarreal        0
realmadrid        0
mancity           0
juventus          0
atleticomadrid    0
leverkeusen       0
liverpool         0

Top 5 brands are:
             0
bayern     523
psg        379
ajax       368
chelsea    240
barcelona  234

Top 5 attributes are:
        0
good  946
bad   303

Top 10 attributes are:
        0
good  946
bad   303

In [75]:
df_tk_pre[df_tk_pre.columns[0]]

0        [pre-match thread] porto vs juventus (champion...
1        [pre-match thread] porto vs juventus (champion...
2        [pre-match thread] porto vs juventus (champion...
3        [pre-match thread] porto vs juventus (champion...
4        [pre-match thread] porto vs juventus (champion...
                               ...
20038    [pre match thread] liverpool vs manchester cit...
20039    [pre match thread] liverpool vs manchester cit...
20040    [pre match thread] liverpool vs manchester cit...
20041    [pre match thread] liverpool vs manchester cit...
20042    [pre match thread] liverpool vs manchester cit...
Name: ptitle, Length: 20043, dtype: object

In [34]:
df_tk_pre['comment'][0]

['stop',
 'sporting',
 'winning',
 'league',
 'least',
 'make',
 'country',
 'proud',
 'winning',
 'Lyond',
 'lady']

In [6]:
teams_association = pd.DataFrame(0, columns=top10_team_names, index=top10_team_names)
teams_association

,liverpool,inter,tottenham,barcelona,ajax,chelsea,psg,bayern,arsenal,realmadrid
liverpool,0,0,0,0,0,0,0,0,0,0
inter,0,0,0,0,0,0,0,0,0,0
tottenham,0,0,0,0,0,0,0,0,0,0
barcelona,0,0,0,0,0,0,0,0,0,0
ajax,0,0,0,0,0,0,0,0,0,0
chelsea,0,0,0,0,0,0,0,0,0,0
psg,0,0,0,0,0,0,0,0,0,0
bayern,0,0,0,0,0,0,0,0,0,0
arsenal,0,0,0,0,0,0,0,0,0,0
realmadrid,0,0,0,0,0,0,0,0,0,0